import hashlib
import re

import requests


REFERENCE_PERTURBATIONS = [
    "paraphrase",
    "reordering",
    "formatting",
    "context_injection",
    "surface_noise",
]


_ESSENTIAL_WORDS = {
    "answer",
    "answers",
    "unanswerable",
    "positive",
    "negative",
    "acceptable",
    "unacceptable",
    "entailment",
    "not_entailment",
    "not",
    "python",
    "code",
    "function",
    "true",
    "false",
}


def perturb_instruction(
    text: str,
    perturbation: str,
    task: str,
    api_key: str | None = None,
    model: str = "gpt-4o-mini",
) -> str:
    if perturbation == "paraphrase":
        return generate_llm_rephrasing(text, api_key, model, mode="paraphrase")
    if perturbation == "reordering":
        return generate_llm_rephrasing(text, api_key, model, mode="reordering")
    if perturbation == "formatting":
        return apply_posix_prompt_template(text)
    if perturbation == "context_injection":
        return inject_context(text)
    if perturbation == "surface_noise":
        return add_surface_noise(text)
    raise ValueError(f"Unknown perturbation: {perturbation}")


def generate_llm_rephrasing(text: str, api_key: str | None, model: str, mode: str) -> str:
    if not api_key:
        raise RuntimeError(
            f"{mode} follows the POSIX / sensitivity-consistency reference method and must be generated by an LLM sampler."
        )
    if mode == "paraphrase":
        instruction = (
            "Generate one intent-preserving paraphrase of the following task instruction. "
            "Preserve all labels, required output constraints, function names, and answerability rules. "
            "Do not solve the task. Return only the paraphrased instruction."
        )
    elif mode == "reordering":
        # Proposal-specific implementation: the reference PDFs motivate prompt
        # rephrasing/template variation, but do not give a deterministic
        # reordering algorithm. Keep this as an LLM-sampled semantic-preserving
        # clause-order change rather than a hand-written task template.
        instruction = (
            "Generate one semantically equivalent version of the following task instruction by changing only "
            "the order of clauses or information presentation. Preserve all labels, required output constraints, "
            "function names, and answerability rules. Do not solve the task. Return only the reordered instruction."
        )
    else:
        raise ValueError(f"Unknown LLM rephrasing mode: {mode}")

    response = requests.post(
        "https://api.openai.com/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": model,
            "messages": [
                {
                    "role": "system",
                    "content": "You rewrite task instructions while preserving intent exactly.",
                },
                {"role": "user", "content": f"{instruction}\n\nInstruction:\n{text}"},
            ],
            "temperature": 0.7,
            "top_p": 0.9,
        },
        timeout=90,
    )
    if response.status_code >= 400:
        raise RuntimeError(f"{response.status_code} {response.text[:1000]}")
    return response.json()["choices"][0]["message"]["content"].strip().strip('"')


def apply_posix_prompt_template(text: str) -> str:
    # POSIX Appendix B uses template variants such as "Question:{}\nAnswer:" / "q:{}\na:".
    return f"Question: {text}\nAnswer:"


def inject_context(text: str) -> str:
    # PromptRobust sentence-level attacks append irrelevant material to the prompt.
    return f"{text.rstrip().rstrip('.')} and false is not true."


def add_surface_noise(text: str, edits: int = 4) -> str:
    if edits <= 0:
        return text
    tokens = re.findall(r"[A-Za-z]+|[^A-Za-z]+", text)
    word_positions = [
        idx
        for idx, token in enumerate(tokens)
        if token.isalpha()
        and len(token) > 3
        and token.lower() not in _ESSENTIAL_WORDS
    ]
    if not word_positions:
        return text

    offset = int(hashlib.sha256(text.encode("utf-8")).hexdigest()[:8], 16) % len(word_positions)
    selected = [word_positions[(offset + step) % len(word_positions)] for step in range(min(edits, len(word_positions)))]
    operations = [_insert_char, _omit_char, _transpose_chars, _substitute_keyboard_neighbor]
    for op_idx, token_idx in enumerate(selected):
        tokens[token_idx] = operations[op_idx % len(operations)](tokens[token_idx])
    return "".join(tokens)


def _insert_char(word: str) -> str:
    pos = max(1, len(word) // 2)
    return word[:pos] + word[pos - 1] + word[pos:]


def _omit_char(word: str) -> str:
    pos = max(1, len(word) // 2)
    return word[:pos] + word[pos + 1 :]


def _transpose_chars(word: str) -> str:
    if len(word) < 4:
        return word
    pos = max(1, len(word) // 2 - 1)
    chars = list(word)
    chars[pos], chars[pos + 1] = chars[pos + 1], chars[pos]
    return "".join(chars)


def _substitute_keyboard_neighbor(word: str) -> str:
    neighbors = {
        "a": "s",
        "e": "w",
        "i": "o",
        "o": "p",
        "s": "a",
        "t": "r",
        "n": "m",
        "r": "e",
        "l": "k",
    }
    pos = max(1, len(word) // 2)
    chars = list(word)
    lower = chars[pos].lower()
    replacement = neighbors.get(lower, "x")
    chars[pos] = replacement.upper() if chars[pos].isupper() else replacement
    return "".join(chars)
